### ISSUE TITLE
CRLF line terminators in 03_setup_root_path.sh lead on an error on container launch

### ISSUE THREAD

**Issue by robertkck** [openanalytics/shinyproxy-rstudio-ide-demo#2]
Hi,
Thank you for the great project. 
As far as I can tell, `03_setup_root_path.sh` is set up with CRLF line terminators.
```
$ file 03_setup_root_path.sh
03_setup_root_path.sh: a /usr/bin/with-contenv bash script, ASCII text executable, with CRLF line terminators
``` 
This leads to an error wheh the container is launched: 
```
[cont-init.d] 03_setup_root_path.sh: executing...
: No such file or directory bash
[cont-init.d] 03_setup_root_path.sh: exited 127.
``` 
Switching to LF line endings fixed the problem for me. 

I would support this with a pull request, but I am not sure if the problem only occurs because I am using a Windows OS. 
Best,
Robert

**Comment by LEDfan** [comment]
Hi

As I understand you are using Windows + some Linux emulation layer (WSL, cygwin ...). I think the problem is that when you clone this repository on Windows, Git changes the line endings to CRLF. However, when you then switch to your Linux emulation, you have a problem because it wants to use LF endings and not CRLF. I think you can solve this by changing the autocrlf option of Git (https://stackoverflow.com/a/20653073/1393103) or by using Git on the Linux emulation as well.

I made a fresh clone of this repository and the line endings stay at LF:
```bash
    $ file 03_setup_root_path.sh 
03_setup_root_path.sh: a /usr/bin/with-contenv bash script, ASCII text executable
````

**Comment by robertkck** [comment]
Thanks for the reply. Sorry about that. The issue appears to have been on my end.
